/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ece651.riskgame.server;

import java.io.IOException;

public class App {
  public RiskGame riskGame;

  public App(int n) throws IOException {
    riskGame = new RiskGame(n);
  }

  public static void main(String[] args) {    
    if ((args.length != 1) || (args[0].length() != 1) || args[0].charAt(0) < '1' || args[0].charAt(0) > '5') {
      System.out.println("Player number 2-5");
      return;
    }  
    int playerNum = Integer.parseInt(args[0]);
    try{
      App app = new App(playerNum);
      app.riskGame.run();
    }
    catch (IOException e) {
      System.out.println("IOException ouucred, server shut down");
    }
  }
}
