/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ece651.riskgame.server;

import java.io.IOException;

public class App {
  public RiskGame riskGame;

  public App() {
    riskGame = new RiskGame();
  }

  public static void main(String[] args) {
    App app = new App();
    try{
      app.riskGame.run();
    }
    catch (IOException e) {
      System.out.println("IOException ouucred, server shut down");
    }
  }
}
