 /*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ece651.riskgame.client;

import java.io.IOException;
import java.net.URL;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;

public class App extends Application {

  @Override  
  public void start(Stage stage) throws IOException {
    URL xmlResource = getClass().getResource("/ui/main-page.xml");
    System.out.println(xmlResource);
    
    FXMLLoader loader = new FXMLLoader(xmlResource);
    GridPane gp = loader.load();

    Scene scene = new Scene(gp, 800, 600);
    stage.setScene(scene);
    stage.show();
  }

  public static void main(String[] args) {
    launch();
  }

}
 
