/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ece651.riskgame.client;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.List;
import java.util.Map;

import ece651.riskgame.shared.GameInfo;
import ece651.riskgame.shared.Territory;
import ece651.riskgame.shared.Unit;

public class App {
  //private TextPlayer player;
  //private String serverIp;

  @SuppressWarnings("unchecked")
  public static void main(String[] args) throws IOException{
    String ip = args[0];
    int port = -1;
    try {
      port = Integer.parseInt(args[1]);
    }
    catch (NumberFormatException e) {
      System.err.println("Argument" + args[1] + " must be an integer.");
      System.exit(1);
    }
    //connect to server
    Socket serverSocket = null;
    ObjectInputStream socketIn = null;
    ObjectOutputStream socketOut = null;
    try {
      serverSocket = new Socket(ip, port);
      socketIn = new ObjectInputStream(serverSocket.getInputStream());
      socketOut = new ObjectOutputStream(serverSocket.getOutputStream());
    } catch (UnknownHostException e) {
      System.err.println("Don't know about host: " + ip);
      System.exit(1);
    }
    System.out.println("Connection Estabilished");
    TextPlayer p = null;
    //recv allocated player color
    //recv GameInfo
    //recv Initial Units
    String color = null;
    GameInfo game = null;
    List<Unit> units = null;
    try {
      color = (String) socketIn.readObject();
      game = (GameInfo) socketIn.readObject();
      units = (List<Unit>) socketIn.readObject();
    } catch (ClassNotFoundException e) {
      System.err.println("Class Not Found when reading Object through socket");
      System.exit(1);
    }
    p = new TextPlayer(color, game);
    

    p.display();
    Map<Unit, Territory> placements = p.doPlacementPhase(units);
    System.out.print(placements);
    socketOut.writeObject(placements);
    
    socketIn.close();
    serverSocket.close();
    System.exit(0);
    }
}
