/*
* This Java source file was generated by the Gradle 'init' task.
*/
package ece651.riskgame.client;

import java.io.IOException;
import java.net.URL;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.GridPane;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class RiscApplication extends Application {

  private AppIO appIO;
  // Models
  // GUIPlayer
  
  /**
   * Method called to launch the frontend application
   */
  public static void main(String[] args) {
    launch();
  }

  @Override
  public void start(Stage stage) throws IOException {
    appIO = new AppIO(new String[] {"0.0.0.0", "1651"});
    
    URL xmlResource = getClass().getResource("/ui/main-page.xml");
    System.out.println(xmlResource);

    FXMLLoader loader = new FXMLLoader(xmlResource);
    GridPane gp = loader.load();

    Scene scene = new Scene(gp, 800, 600);
    URL cssResource = getClass().getResource("/ui/css/game-map.css");
    scene.getStylesheets().add(cssResource.toString());

    
    setUserName(scene, appIO.getColor());
    
    stage.setScene(scene);
    stage.show();
    

    
  }
  
  /**
   * Method to set username in UI
   */
  private void setUserName(Scene scene, String value) {
    Text usernameText = (Text) scene.lookup("#topBar").lookup("#username");
    usernameText.setText(value);    
  }
}
